services:
  node_app:
    container_name: flow_bank
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '80:80'
    env_file:
      - .env
    networks:
      - app-network

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - '16686:16686' # Jaeger UI
      - '4317:4317' # OTLP gRPC receiver for traces
    networks:
      - app-network

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - '9090:9090'
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
