services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db
    networks:
      - app-network
  node_app:
    container_name: node_app
    image: killbash/flow-bank:latest
    ports:
      - '3000:3000'
    env_file:
      - .env
    depends_on:
      - mongo
    networks:
      - app-network


volumes:
  mongo_data:

networks:
  app-network:
    driver: bridge
