# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:

  pull_request:
    branches: [ "main",  "dev" ]
    

jobs:
  test:
    if: github.base_ref == 'main' || github.base_ref == 'dev'

    runs-on: ubuntu-latest


    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
    - name: Install dependencies
      run: npm install
    - name: Run lint
      run: npm run check
    - name: Run test
      run: npm test

  

  build_and_publish:

    if: github.base_ref == 'main'

    runs-on: ubuntu-latest
    needs: test

    environment: flow


    permissions:
      contents: read
      packages: write 
      actions: write

    steps:
        - name: Checkout code
          uses: actions/checkout@v3
  
        - name: Log in to GitHub Container Registry
          uses: docker/login-action@v2
          with:
              registry: ghcr.io
              username: bash360
              password: ${{ secrets.TOKEN }}

        - name: Build Docker image
          run: docker build -t ghcr.io/${{ github.repository }}:latest .
        
        - name: Push Docker image
          run: docker push ghcr.io/${{ github.repository }}:latest
  

